trait_param_mut_prob 0.5
trait_mutation_power 1.0
linktrait_mut_sig 1.0
nodetrait_mut_sig 0.5
weight_mut_power 0.75
recur_prob 0.05
disjoint_coeff 1.0
excess_coeff 2.0
mutdiff_coeff 0.0
gru_compat_coeff 0.0
compat_thresh 3.0
age_significance 1.0
survival_thresh 0.4
mutate_only_prob 1.0
mutate_random_trait_prob 0.1
mutate_link_trait_prob 0.1
mutate_node_trait_prob 0.1
mutate_link_weights_prob 0.8
mutate_gru_link_weights_prob 0.5
mutate_toggle_enable_prob 0.05
mutate_gene_reenable_prob 0.5
mutate_add_node_prob 0.1
mutate_gru_add_node_prob 0.2
mutate_add_link_prob 0.5
interspecies_mate_rate 0.001
mate_multipoint_prob 0.6
mate_multipoint_avg_prob 0.4
mate_singlepoint_prob 0.0
mate_only_prob 0.2
recur_only_prob 0.2
pop_size 150
dropoff_age 25
newlink_tries 20
print_every 199
babies_stolen 0
num_runs 1
num_gens 500
num_trials 1
